# Generated by Django 6.1.1 on 2026-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Не отработан'), ('cooking', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Выполнен')], db_index=True, default='pending', max_length=20, verbose_name='статус'),
        ),
    ]
