# Generated by Django 6.1.1 on 2026-09-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно')], db_index=True, max_length=20, null=True, verbose_name='способ оплаты'),
        ),
    ]
